server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xwl?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.display.model



